### ISSUE TITLE
Installation OpenVolunteer

### ISSUE THREAD

**Issue by ttetelin** [lrivallain/openvolunteer#32]
Bonjour, 

Votre système de gestion m'intéresse beaucoup, je m'occupe d'un festival de musique dans le sud ouest.

Je gère aujourd'hui prés de 200 bénévoles et votre système nous faciliterai considérablement la tache ! 

Est ce que vous pouvez me fournir un document détaillant la procédure d'installation?

J'ai un hébergement chez OVH, est ce que c'est possible d'installer votre système sur mon hébergement ? 

Merci,

**Comment by lrivallain** [comment]
Bonjour,

Malheureusement je n'ai plus de temps pour travailler ou aider sur OpenVolunteer.

Si tu n'as pas déjà trouvé de solution, et que Openvolunteer est trop "brut de décoffrage" en l'état, tu peux essayer:
- http://festivit.org/ (asso qui bosse dans ce domaine)
- https://www.calligra.org/plan/ (qui peut faire le job moyennant un peu de souplesse dans l'usage)

Bon courage.

**Comment by ttetelin** [comment]
Bonjour , 

Merci pour les infos , 

Cdt,

T.T
ttetelin@gmail.com
www.ttetelin.free.fr
